### ISSUE TITLE
question i dont know how to use the project 

### ISSUE THREAD

**Issue by fadwaJB** [rokkuran/stegasawus#1]
Hi 
pleas i need help to use the project  to detect a hidden message in support image . 
i am beginner and i cant find steps in README or any other place
thanx

**Comment by rokkuran** [comment]
I haven't looked at this project in a few years but from memory:

- First you need to generate your embedded images using dataset.py
- Then create your feature set csv files from the data you created using features.py

There are a couple of example scripts in the examples directory.

You can then run the models.py code to compare the various models you're interested in looking at.

I haven't included the code to generate the plot in the readme but it's just a seaborn pairplot or something like that.

There are also a few nice plots that show the differences in the images and the wavelet decompositions that some of the features are based off.

The repo could use a bit of work.
